name: Maven Package

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set Maven Version
        run: |
          TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          sed -i "s/1\.0-SNAPSHOT/${TAG}/" pom.xml
          - name: Set up JDK 21
            uses: actions/setup-java@v3
            with:
              java-version: '21'
              distribution: 'temurin'
              server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
              settings-path: ${{ github.workspace }} # location for the settings.xml file

          - name: Build with Maven
            run: mvn -B package --file pom.xml

          - name: Publish to GitHub Packages Apache Maven
            run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
            env:
              GITHUB_TOKEN: ${{ github.token }}
